/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#141313',
          dim: '#141313',
          bright: '#3a3939',
          'container-lowest': '#0e0e0e',
          'container-low': '#1c1b1b',
          container: '#201f1f',
          'container-high': '#2a2a2a',
          'container-highest': '#353434',
          tint: '#a5c8ff',
          variant: '#353434',
        },
        'on-surface': {
          DEFAULT: '#e5e2e1',
          variant: '#c3c6d0',
        },
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: {
          DEFAULT: '#8d919a',
          variant: '#43474f',
        },
        primary: {
          DEFAULT: '#a5c8ff',
          container: '#295892',
          fixed: '#d4e3ff',
          'fixed-dim': '#a5c8ff',
        },
        'on-primary': {
          DEFAULT: '#00315f',
          container: '#b2cfff',
          fixed: '#001c3a',
          'fixed-variant': '#124780',
        },
        'inverse-primary': '#325f99',
        secondary: {
          DEFAULT: '#a5c9fc',
          container: '#234a77',
          fixed: '#d3e4ff',
          'fixed-dim': '#a5c9fc',
        },
        'on-secondary': {
          DEFAULT: '#00315c',
          container: '#97bbed',
          fixed: '#001c38',
          'fixed-variant': '#214874',
        },
        tertiary: {
          DEFAULT: '#c6c6c6',
          container: '#565757',
          fixed: '#e2e2e2',
          'fixed-dim': '#c6c6c6',
        },
        'on-tertiary': {
          DEFAULT: '#2f3131',
          container: '#cdcdcd',
          fixed: '#1a1c1c',
          'fixed-variant': '#454747',
        },
        error: {
          DEFAULT: '#ffb4ab',
          container: '#93000a',
        },
        'on-error': {
          DEFAULT: '#690005',
          container: '#ffdad6',
        },
        'status-accent': {
          rose: '#ff9e9e',
          amber: '#ffd37c',
          lavender: '#d6c8ff',
        },
        background: '#141313',
        'on-background': '#e5e2e1',
      },
      fontFamily: {
        heading: ["'Poppins'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '0.95', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-xl-mobile': ['48px', { lineHeight: '1', letterSpacing: '-0.05em', fontWeight: '800' }],
        'display-lg': ['56px', { lineHeight: '1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md-mobile': ['22px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-lg': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md-mobile': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'code-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        'container-max': '1440px',
        gutter: '48px',
        'margin-mobile': '20px',
        'stack-xl': '160px',
        'stack-lg': '120px',
        'stack-md': '80px',
        'stack-sm': '40px',
        'stack-mobile-xl': '80px',
        'stack-mobile-lg': '60px',
        'stack-mobile-md': '40px',
      },
    },
  },
  plugins: [],
};

